"""Generators that emit TypeScript / JSON artifacts consumed by the in-repo transformer."""

import json
from collections import OrderedDict
from pathlib import Path
from typing import Any

from .predicates import _is_ddi_emittable
from .util import _slug, _ts_key


def generate_typescript(registry: dict[str, Any], output: Path):
    """Generate TypeScript type mappings for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " */",
        "",
        "export type TypeKind = 'question' | 'metadata' | 'structural';",
        "",
        "export interface TypeMapping {",
        "  kind: TypeKind;",
        "  limeSurveyType: string | null;",
        "  supported: boolean;",
        "  supportsOther?: boolean;",
        "  answerClass?: 'A' | 'SQ' | null;",
        "  requiresListName?: boolean;",
        "  dateFormat?: string;",
        "}",
        "",
        "export const TYPE_MAPPINGS: Record<string, TypeMapping> = {",
    ]

    def emit(name: str, kind: str, data: dict):
        ls = data.get("limesurvey", {})
        xls = data.get("xlsform", {})
        supported = ls.get("supported", True) if ls else True
        # If typeCode missing and not explicitly supported=true, treat as unsupported
        if ls.get("typeCode") is None and "supported" not in ls:
            supported = False
        lines.append(f"  {_ts_key(name)}: {{")
        lines.append(f"    kind: {json.dumps(kind)},")
        lines.append(f"    limeSurveyType: {json.dumps(ls.get('typeCode'))},")
        lines.append(f"    supported: {'true' if supported else 'false'},")
        if ls.get("supportsOther"):
            lines.append("    supportsOther: true,")
        if ls.get("answerClass"):
            lines.append(f"    answerClass: {json.dumps(ls['answerClass'])},")
        if xls.get("requiresListName"):
            lines.append("    requiresListName: true,")
        if ls.get("dateFormat"):
            lines.append(f"    dateFormat: {json.dumps(ls['dateFormat'])},")
        lines.append("  },")

    kind_map = {
        "QuestionType": "question",
        "StructuralType": "structural",
    }
    for _type_id, data in registry.items():
        kind = kind_map.get(data.get("@type"))
        if kind is None:
            continue
        xlsform = data["xlsform"]["typeString"]
        emit(xlsform, kind, data)
        for alias in data["xlsform"].get("aliases", []):
            emit(alias, kind, data)

    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines))


def generate_typescript_ddi(registry: dict[str, Any], output: Path):  # noqa: C901 (grandfathered; split before extending)
    """Generate TypeScript DDI-Codebook mappings for the DDI emitter (src/ddi/).

    Mirrors generate_python's DDI section: same registry-derived maps, emitted
    as a TS module the in-repo emitter imports. Registry is the single source
    of truth for what maps to what.
    """
    L: list[str] = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " *",
        " * DDI-Codebook 2.5 type mappings consumed by the DDI emitter (src/ddi/).",
        " */",
        "",
        "/** DDI interval classification + varFormat type for a standardized type. */",
        "export type DdiTypeInfo = readonly [intrvl: string, formatType: string];",
        "",
        "/** External code-list vocabulary metadata (long-list pattern). */",
        "export interface Vocabulary {",
        "  ddiVocab: string;",
        "  vocabURI: string;",
        "  standard: string;",
        "  label: string;",
        "}",
        "",
        "/** XLSForm type string → standardized type slug. */",
        "export const TYPE_MAP: Record<string, string> = {",
    ]

    for type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        xlsform = data["xlsform"]["typeString"]
        canon = _slug(type_id)
        L.append(f"  {_ts_key(xlsform)}: {json.dumps(canon)},")
        for alias in data["xlsform"].get("aliases", []):
            L.append(f"  {_ts_key(alias)}: {json.dumps(canon)},")
    L.append("};")
    L.append("")

    L.append("/** XLSForm types with no DDI interval — not emitted as <var> (no ddi.intrvl). */")
    L.append("export const NON_DDI_EMITTABLE_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        if not data.get("ddi", {}).get("intrvl"):
            L.append(f"  {json.dumps(data['xlsform']['typeString'])},")
    L.append("];")
    L.append("")

    L.append("/** XLSForm structural types (begin_group / end_group). */")
    L.append("export const STRUCTURAL_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "StructuralType":
            continue
        xls = data.get("xlsform", {}).get("typeString")
        if xls:
            L.append(f"  {json.dumps(xls)},")
    L.append("];")
    L.append("")

    L.append("/** Standardized type → [intrvl, formatType]. Only DDI-emittable types. */")
    L.append("export const DDI_TYPE_MAP: Record<string, DdiTypeInfo> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        ddi = data["ddi"]
        intrvl = ddi.get("intrvl", "discrete")
        fmt_type = ddi.get("formatType", "character")
        L.append(f"  {_ts_key(_slug(type_id))}: [{json.dumps(intrvl)}, {json.dumps(fmt_type)}],")
    L.append("};")
    L.append("")

    L.append("/** Standardized type → responseDomainType for <qstn>. */")
    L.append("export const RESPONSE_DOMAIN_MAP: Record<string, string> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        rd = data["ddi"].get("responseDomainType")
        if rd:
            L.append(f"  {_ts_key(_slug(type_id))}: {json.dumps(rd)},")
    L.append("};")
    L.append("")

    L.append("/** Standardized type → measurement level. */")
    L.append("export const MEASURE_MAP: Record<string, string> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        ddi = data.get("ddi", {})
        intrvl = ddi.get("intrvl", "")
        xls = data["xlsform"]["typeString"]
        if intrvl == "nominal" or (
            intrvl == "discrete"
            and xls in ["select_one", "select_multiple", "select_one_from_file", "select_multiple_from_file"]
        ):
            measure = "nominal"
        elif intrvl == "ordinal" or xls == "rank":
            measure = "ordinal"
        elif xls in ("date", "time") or intrvl == "interval":
            measure = "interval"
        elif intrvl == "contin":
            measure = "ratio"
        else:
            continue
        L.append(f"  {_ts_key(_slug(type_id))}: {json.dumps(measure)},")
    L.append("};")
    L.append("")

    L.append("/** External code-list vocabularies, keyed by xlsform filename. */")
    L.append("export const VOCABULARIES: Record<string, Vocabulary> = {")
    for _type_id, data in registry.items():
        if data.get("@type") != "Vocabulary":
            continue
        fn = data.get("xlsformFilename")
        if not fn:
            continue
        L.append(f"  {_ts_key(fn)}: {{")
        L.append(f"    ddiVocab: {json.dumps(data.get('ddiVocab', ''))},")
        L.append(f"    vocabURI: {json.dumps(data.get('vocabURI', ''))},")
        L.append(f"    standard: {json.dumps(data.get('standard', ''))},")
        L.append(f"    label: {json.dumps(data.get('skos:prefLabel', ''))},")
        L.append("  },")
    L.append("};")
    L.append("")

    L.append("/** XLSForm types sourcing choices from an external file (emit <concept vocab>). */")
    L.append("export const EXTERNAL_CODELIST_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        if data.get("ddi", {}).get("externalCodeList"):
            L.append(f"  {json.dumps(data['xlsform']['typeString'])},")
    L.append("];")
    L.append("")

    output.write_text("\n".join(L))


def generate_appearances(registry: dict[str, Any], output: Path):
    """Emit Appearance entries as TS map for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " */",
        "",
        "export interface AppearanceSpec {",
        "  supported: boolean;",
        "  behavior: 'handled' | 'warn';",
        "  validForTypes?: string[];",
        "  lsEffect: string;",
        "  lsTypeOverride?: string;",
        "  /** False when a row bearing this appearance stores no response (matrix header). */",
        "  carriesData?: boolean;",
        "}",
        "",
        "export const APPEARANCES: Record<string, AppearanceSpec> = {",
    ]
    # Build alias map: typeString -> [typeString, ...aliases]
    alias_map: dict[str, list[str]] = {}
    for data in registry.values():
        if data.get("@type") != "QuestionType":
            continue
        xls = data.get("xlsform", {})
        primary = xls.get("typeString")
        if not primary:
            continue
        alias_map[primary] = [primary, *list(xls.get("aliases", []))]

    def expand_types(types: list[str]) -> list[str]:
        out: list[str] = []
        seen: set[str] = set()
        for t in types:
            for x in alias_map.get(t, [t]):
                if x not in seen:
                    seen.add(x)
                    out.append(x)
        return out

    for _type_id, data in registry.items():
        if data.get("@type") != "Appearance":
            continue
        aid = data["xlsform"]["appearanceString"]
        lines.append(f"  {json.dumps(aid)}: {{")
        lines.append(f"    supported: {'true' if data['supported'] else 'false'},")
        lines.append(f"    behavior: {json.dumps(data['behavior'])},")
        if data.get("validForTypes"):
            expanded = expand_types(data["validForTypes"])
            lines.append(f"    validForTypes: {json.dumps(expanded)},")
        lines.append(f"    lsEffect: {json.dumps(data['lsEffect'])},")
        if data.get("lsTypeOverride"):
            lines.append(f"    lsTypeOverride: {json.dumps(data['lsTypeOverride'])},")
        # Only emitted when explicitly false — absence means "carries data".
        if data.get("carriesData") is False:
            lines.append("    carriesData: false,")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    output.write_text("\n".join(lines))


def _conventions_payload(registry: dict[str, Any]) -> dict[str, Any]:
    """Global conventions + column map + composites, in emit order."""
    conv = {}
    col_map = []
    composites = []
    for _type_id, data in registry.items():
        t = data.get("@type")
        if t == "GlobalConvention":
            slug = data["@id"].split(":", 1)[1]
            conv[slug] = data.get("rule", {})
        elif t == "XLSFormColumnMap":
            col_map = data.get("map", [])
        elif t == "Composite":
            composites.append(
                OrderedDict(
                    [
                        ("id", data["@id"].split(":", 1)[1]),
                        ("label", data.get("skos:prefLabel")),
                        ("broader", data.get("skos:broader")),
                        ("trigger", data.get("trigger", {})),
                        ("input", data.get("input", {})),
                        ("output", data.get("output", {})),
                        ("schematronPatterns", data.get("schematronPatterns", [])),
                        ("notes", data.get("notes", [])),
                    ]
                )
            )
    # Sort so output is independent of registry file layout (conventions now
    # live in separate conventions/*.jsonld files loaded by glob).
    conv = {k: conv[k] for k in sorted(conv)}
    composites.sort(key=lambda c: c["id"])
    return {
        "$comment": "GENERATED - DO NOT EDIT. Source: registry/root.jsonld",
        "conventions": conv,
        "xlsformColumnMap": col_map,
        "composites": composites,
    }


def generate_conventions(registry: dict[str, Any], output: Path):
    """Emit global conventions + column map + composites as JSON.

    The JSON is the artifact for non-TypeScript consumers; the library itself
    imports the `.ts` twin written by {@link generate_conventions_ts}.
    """
    payload = _conventions_payload(registry)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")


def generate_conventions_ts(registry: dict[str, Any], output: Path):
    """Emit the same payload as a TypeScript module.

    The library must not `import ... with { type: 'json' }` at runtime: whether
    the JSON reaches `dist/` depends on tsc copying it, and whether a consumer's
    bundler understands import attributes varies by bundler version. A plain
    module sidesteps both — tsc always emits it, every bundler resolves it, and
    the inferred types are identical to the JSON import's.
    """
    payload = json.dumps(_conventions_payload(registry), indent=2, ensure_ascii=False)
    output.write_text(
        "/**\n"
        " * GENERATED CODE - DO NOT EDIT\n"
        " * Source: registry/root.jsonld\n"
        " * Generated by: codegen\n"
        " *\n"
        " * Same payload as `conventions.json`, emitted as a module so the published\n"
        " * library carries no runtime JSON import. Edit the registry, not this file.\n"
        " */\n"
        "\n"
        f"const conventions = {payload};\n"
        "\n"
        "export default conventions;\n"
    )


def _entry_lines(
    key: str,
    *,
    entry_id: str,
    type_string: str | None,
    label: str,
    kind: str,
    use_when: str,
    bases: list[str],
    is_variant: bool,
    is_composite: bool,
    aliases: list[str] | None = None,
    constraints: dict[str, Any] | None = None,
) -> list[str]:
    """One `QUESTION_TYPES` record entry."""
    lines = [
        f"  {_ts_key(key)}: {{",
        f"    id: {json.dumps(entry_id)},",
        f"    label: {json.dumps(label, ensure_ascii=False)},",
        f"    kind: {json.dumps(kind)},",
        f"    useWhen: {json.dumps(use_when, ensure_ascii=False)},",
        f"    isVariant: {'true' if is_variant else 'false'},",
        f"    isComposite: {'true' if is_composite else 'false'},",
    ]
    # Composites get an explicit `undefined` rather than an omitted key: under
    # `as const` an omitted key does not exist on that member's type, and a
    # consumer iterating `Object.values()` then cannot touch `.typeString` at all.
    lines.append(f"    typeString: {json.dumps(type_string) if type_string is not None else 'undefined'},")
    if len(bases) == 1:
        lines.append(f"    base: {json.dumps(bases[0])},")
    elif len(bases) > 1:
        lines.append(f"    bases: {json.dumps(bases)},")
    if aliases:
        lines.append(f"    aliases: {json.dumps(aliases)},")
    if constraints:
        lines.append(f"    constraints: {json.dumps(constraints, ensure_ascii=False)},")
    lines.append("  },")
    return lines


def generate_question_types(registry: dict[str, Any], output: Path):
    """Emit the labelled question-type catalogue consumed by UIs and generators.

    `TYPE_MAPPINGS` answers "how does this type convert"; this answers "what is
    this type called and when is it used" — `skos:prefLabel`, `useWhen`, the
    variant → base relation and the authoring constraints, none of which are
    reachable from the published package otherwise (`files` is `["dist"]`, so
    `registry/` never ships).

    Keyed by registry slug (`select_one`, `select_one_other`, `grid`, `start`),
    which is the vocabulary the converters, the generated skill and the DDI
    output all use.
    """
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld + registry/entities/<slug>/definition.jsonld",
        " * Generated by: codegen",
        " *",
        " * Labelled catalogue of everything a survey row can be. See",
        " * `TypeMappings.ts` for how each type converts.",
        " */",
        "",
        "/** Authoring limits a type imposes on names and choice codes. */",
        "export interface QuestionTypeConstraints {",
        "  maxNameLength?: number;",
        "  namePattern?: string;",
        "  maxChoiceCodeLength?: number;",
        "  choiceCodePattern?: string;",
        "  warnings?: readonly string[];",
        "  /** Registry constraints are open-ended; unlisted keys pass through. */",
        "  [key: string]: unknown;",
        "}",
        "",
        "export interface QuestionTypeEntry {",
        "  /** Registry `@id`, e.g. `type:select_one` or `variant:select_one_other`. */",
        "  id: string;",
        "  /**",
        "   * The XLSForm `type` cell for this row. A variant repeats its base's",
        "   * string, because it is authored as that type plus a convention (a",
        "   * companion `_other` row, a `_from_file` list). Absent on composites:",
        "   * a composite spans several rows, so it has no single type cell.",
        "   */",
        "  typeString?: string;",
        "  /** Display label, from `skos:prefLabel`. */",
        "  label: string;",
        "  /** Methodology guidance, from `useWhen`. Empty for structural rows. */",
        "  useWhen: string;",
        "  kind: 'question' | 'metadata' | 'structural';",
        "  /** Registry slug of the type a variant derives from (`skos:broader`). */",
        "  base?: string;",
        "  /** Composites derive from several types at once, e.g. grid. */",
        "  bases?: readonly string[];",
        "  isVariant: boolean;",
        "  isComposite: boolean;",
        "  /** Accepted alternative `type` strings (e.g. `string` for `text`). */",
        "  aliases?: readonly string[];",
        "  constraints?: QuestionTypeConstraints;",
        "}",
        "",
        "/**",
        " * Keyed by registry slug. Emitted with `as const satisfies` rather than an",
        " * annotation: an annotation would collapse every value to the uniform",
        " * `QuestionTypeEntry` in the `.d.ts`, and consumers deriving a union of",
        " * `typeString` literals would get `never`.",
        " */",
        "export const QUESTION_TYPES = {",
    ]

    def broader_slugs(data: dict[str, Any]) -> list[str]:
        """`skos:broader` is a single node for a variant, a list for a composite."""
        b = data.get("skos:broader")
        nodes = b if isinstance(b, list) else [b] if isinstance(b, dict) else []
        return [_slug(n["@id"]) for n in nodes if isinstance(n, dict) and n.get("@id")]

    kinds = {"QuestionType": "question", "StructuralType": "structural"}
    for type_id, data in sorted(registry.items()):
        t = data.get("@type")
        slug = _slug(type_id)
        if t in kinds:
            lines += _entry_lines(
                slug,
                entry_id=type_id,
                type_string=data["xlsform"]["typeString"],
                label=data.get("skos:prefLabel", slug),
                kind=kinds[t],
                use_when=data.get("useWhen", ""),
                bases=[],
                is_variant=False,
                is_composite=False,
                aliases=data["xlsform"].get("aliases"),
                constraints=data.get("constraints"),
            )
        elif t in ("QuestionTypeVariant", "Composite"):
            bases = broader_slugs(data)
            is_variant = t == "QuestionTypeVariant"
            # A variant is authored as its base type; a composite spans rows and
            # has no single type cell, so it gets none.
            type_string = None
            if is_variant and len(bases) == 1:
                type_string = registry.get(f"type:{bases[0]}", {}).get("xlsform", {}).get("typeString")
            lines += _entry_lines(
                slug,
                entry_id=type_id,
                type_string=type_string,
                label=data.get("skos:prefLabel", slug),
                kind="question",
                use_when=data.get("useWhen", ""),
                bases=bases,
                is_variant=is_variant,
                is_composite=not is_variant,
            )

    # Metadata rows are not registry entities — they come from the
    # unregisteredRows convention, which gives their names and one shared
    # behaviour note and nothing else. Emitted so a consumer enumerating row
    # types sees them, with the note as `useWhen` rather than invented prose.
    unreg = next(
        (d.get("rule", {}) for d in registry.values() if d.get("@id") == "convention:unregisteredRows"),
        {},
    )
    behavior = unreg.get("metadataBehavior", "")
    for row in unreg.get("metadataRowTypes", []):
        lines += _entry_lines(
            row,
            entry_id=f"metadataRow:{row}",
            type_string=row,
            label=row,
            kind="metadata",
            use_when=behavior,
            bases=[],
            is_variant=False,
            is_composite=False,
        )

    lines.append("} as const satisfies Record<string, QuestionTypeEntry>;")
    lines.append("")

    # Compile-time guard. A vitest assertion cannot see type widening — dropping
    # `as const` leaves the runtime payload identical and only the .d.ts poorer —
    # so the check lives here, where `npm run typecheck` (and therefore CI) fails
    # on it. Keyed to a real registry slug so it cannot drift from the data.
    guard = next(
        (
            (_slug(tid), d["xlsform"]["typeString"])
            for tid, d in sorted(registry.items())
            if d.get("@type") == "QuestionType"
        ),
        None,
    )
    if guard:
        guard_slug, guard_type = guard
        lines += [
            "/** Fails to compile if the `as const` above is lost and the literals widen. */",
            "type AssertTrue<T extends true> = T;",
            "export type LiteralTypeStringsPreserved = AssertTrue<",
            f"  (typeof QUESTION_TYPES)[{json.dumps(guard_slug)}]['typeString'] extends {json.dumps(guard_type)}",
            "    ? true",
            "    : false",
            ">;",
            "",
        ]

    output.write_text("\n".join(lines))
