"""Generate a self-contained Claude Code sub-skill from the registry.

The registry is the single source of truth for which answer types exist and what
XLSForm syntax is allowed. This emitter renders that into a nested skill
(`skills/cdl-survey-types/`) that a parent survey-generator skill (formulaid's
`generating-xlsforms`) includes: the parent owns the workflow (intake, qwac
search, delivery); this sub-skill owns the authoritative "which type + how to
write it in XLSForm" reference.

Output layout (mirrors formulaid's own SKILL.md + references/ shape):

    skills/cdl-survey-types/
      SKILL.md                       frontmatter + pick-a-type table + index
      references/question-types.md   per-type detail, variants, worked examples
      references/xlsform-syntax.md    naming, or_other, logic, appearances, settings

Everything below the frontmatter is derived — re-running codegen overwrites it.
"""

import json
from pathlib import Path
from typing import Any

SKILL_NAME = "cdl-survey-types"

_DO_NOT_EDIT = (
    "<!-- GENERATED by codegen (codegen/emit_skill.py) from the formtransform registry. "
    "DO NOT EDIT BY HAND — edit registry/ and re-run `uv run codegen`. -->\n"
)


def _load_example(base_dir: Path, entry: dict[str, Any]) -> dict[str, Any] | None:
    """Read an entity's xlsform.json worked example, if it has one on disk."""
    ex = entry.get("examplePath") or (f"{entry['exampleDir']}/xlsform.json" if entry.get("exampleDir") else None)
    if not ex:
        return None
    path = base_dir / ex
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _fmt_example(example: dict[str, Any]) -> str:
    """Compact JSON block of an xlsform.json fixture (survey + choices)."""
    trimmed = {k: example[k] for k in ("survey", "choices") if example.get(k)}
    return "```json\n" + json.dumps(trimmed, indent=2, ensure_ascii=False) + "\n```"


def _skill_md(registry: dict[str, Any]) -> str:
    """SKILL.md — frontmatter + the pick-a-type table (useWhen) + index."""
    qtypes = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionType"),
        key=lambda d: d["xlsform"]["typeString"],
    )
    variants = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionTypeVariant"),
        key=lambda d: d["@id"],
    )
    composites = sorted(
        (d for d in registry.values() if d.get("@type") == "Composite"),
        key=lambda d: d["@id"],
    )

    rows = ["| XLSForm `type` | Name | Use when |", "|---|---|---|"]
    for d in qtypes:
        ts = d["xlsform"]["typeString"]
        rows.append(f"| `{ts}` | {d.get('skos:prefLabel', ts)} | {d.get('useWhen', '—')} |")

    vrows = ["| Variant | Base | Use when |", "|---|---|---|"]
    for d in variants:
        base = d.get("skos:broader", {})
        base_id = base.get("@id", "") if isinstance(base, dict) else ""
        base_slug = base_id.split(":", 1)[1] if ":" in base_id else base_id
        vrows.append(f"| `{d['@id'].split(':', 1)[1]}` | `{base_slug}` | {d.get('useWhen', '—')} |")

    crows = ["| Composite | Use when |", "|---|---|"]
    for d in composites:
        crows.append(f"| `{d['@id'].split(':', 1)[1]}` | {d.get('useWhen', '—')} |")

    desc = (
        "The authoritative catalogue of survey answer types and the XLSForm syntax "
        "allowed by the CDL survey pipeline (formtransform). Include this "
        "sub-skill from a survey-generator skill to pick the right question type and "
        "emit valid XLSForm. The registry is an allowlist: any type not listed here is "
        "rejected downstream."
    )

    return (
        "---\n"
        f"name: {SKILL_NAME}\n"
        f'description: "{desc}"\n'
        "---\n\n"
        f"{_DO_NOT_EDIT}\n"
        "# CDL Survey Answer Types & XLSForm Syntax\n\n"
        "Generated from the [`formtransform`](https://github.com/) — the single "
        "source of truth for the CDL survey pipeline (XLSForm → LimeSurvey TSV / DDI). "
        "**This is an allowlist.** Only the types below are valid; any other survey-sheet "
        "`type` aborts the transformation.\n\n"
        "## Pick a question type\n\n"
        + "\n".join(rows)
        + "\n\n### Variants (a base type under a presentation modifier)\n\n"
        + "\n".join(vrows)
        + "\n\n### Composites (one question spanning several rows)\n\n"
        + "\n".join(crows)
        + "\n\n## References\n\n"
        "| File | Contents |\n"
        "|------|----------|\n"
        "| [references/question-types.md](references/question-types.md) | "
        "Per-type detail: XLSForm `type` string, constraints, variants, worked example. |\n"
        "| [references/xlsform-syntax.md](references/xlsform-syntax.md) | "
        "Allowed XLSForm syntax: naming rules, choice sheet, `or_other`, skip/validation "
        "logic, appearances, `settings` sheet, metadata rows. |\n\n"
        "Read both reference files before emitting XLSForm.\n"
    )


def _question_types_md(registry: dict[str, Any], base_dir: Path) -> str:
    qtypes = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionType"),
        key=lambda d: d["xlsform"]["typeString"],
    )
    variants_by_base: dict[str, list[dict]] = {}
    for d in registry.values():
        if d.get("@type") != "QuestionTypeVariant":
            continue
        base = d.get("skos:broader", {})
        base_id = base.get("@id", "") if isinstance(base, dict) else ""
        variants_by_base.setdefault(base_id, []).append(d)

    out = [_DO_NOT_EDIT, "# Question Types (detail)\n"]

    for d in qtypes:
        ts = d["xlsform"]["typeString"]
        out.append(f"## `{ts}` — {d.get('skos:prefLabel', ts)}\n")
        out.append(f"**Use when:** {d.get('useWhen', '—')}\n")

        aliases = d["xlsform"].get("aliases")
        if aliases:
            out.append(f"**Accepted aliases:** {', '.join(f'`{a}`' for a in aliases)}\n")
        if d["xlsform"].get("requiresListName"):
            out.append(
                "**Requires a choice list:** write the type cell as "
                f"`{ts} <list_name>` and define the options on the `choices` sheet under "
                "that `list_name`.\n"
            )

        c = d.get("constraints", {})
        if c:
            cl = []
            if "maxNameLength" in c:
                cl.append(f"variable `name` ≤ {c['maxNameLength']} chars, `{c.get('namePattern', '')}`")
            if "maxChoiceCodeLength" in c:
                cl.append(f"choice code ≤ {c['maxChoiceCodeLength']} chars, `{c.get('choiceCodePattern', '')}`")
            if cl:
                out.append("**Constraints:** " + "; ".join(cl) + "\n")
            for w in c.get("warnings", []):
                out.append(f"> ⚠️ {w}\n")

        vs = variants_by_base.get(d["@id"], [])
        if vs:
            out.append("**Variants:**\n")
            for v in sorted(vs, key=lambda x: x["@id"]):
                out.append(f"- `{v['@id'].split(':', 1)[1]}` — {v.get('skos:prefLabel', '')}: {v.get('useWhen', '—')}")
            out.append("")

        example = _load_example(base_dir, d)
        if example:
            out.append("**Example:**\n")
            out.append(_fmt_example(example) + "\n")

        # Worked examples for this type's variants (e.g. the _other companion row).
        for v in sorted(vs, key=lambda x: x["@id"]):
            vex = _load_example(base_dir, v)
            if vex:
                out.append(f"**Example — `{v['@id'].split(':', 1)[1]}`:**\n")
                out.append(_fmt_example(vex) + "\n")

    return "\n".join(out) + "\n"


def _syntax_md(registry: dict[str, Any]) -> str:
    def conv(cid: str) -> dict:
        return registry.get(cid, {}).get("rule", {})

    san = conv("convention:sanitization")
    other = conv("convention:other")
    ext = conv("convention:externalCodeList")
    logic = conv("convention:logicMapping")
    lang = conv("convention:languageTagging")
    settings = conv("convention:surveySettings")
    unreg = conv("convention:unregisteredRows")

    appearances = sorted(
        (d for d in registry.values() if d.get("@type") == "Appearance"),
        key=lambda d: d["xlsform"]["appearanceString"],
    )
    vocabs = sorted(
        (d for d in registry.values() if d.get("@type") == "Vocabulary"),
        key=lambda d: d.get("xlsformFilename", ""),
    )

    out = [_DO_NOT_EDIT, "# Allowed XLSForm Syntax\n"]

    # Allowlist note
    if unreg:
        meta_rows = ", ".join(f"`{r}`" for r in unreg.get("metadataRowTypes", []))
        out.append("## Row types are an allowlist\n")
        out.append(
            f"{unreg.get('unknownTypeBehavior', '')}\n\n"
            f"Metadata rows ({meta_rows}) are accepted and carried but produce no authored "
            "question. Every other `type` must be one of the registered question / structural "
            "types.\n"
        )

    # Naming & choice codes
    if san:
        n = san.get("name", {})
        cc = san.get("choiceCode", {})
        out.append("## Names & choice codes\n")
        out.append(
            "Author names/codes in English `snake_case`. Downstream (LimeSurvey) "
            f"sanitization strips `{san.get('name', {}).get('stripCharsRegex', '[_-]')}` "
            f"to the pattern `{n.get('pattern', '')}` and truncates, so keep the "
            "alphanumeric stem short and unambiguous:\n"
            f"- **Variable `name`:** ≤ {n.get('maxLength', '?')} chars after stripping. "
            "Must be unique — duplicates get a numeric suffix.\n"
            f"- **Choice `name` (code):** ≤ {cc.get('maxLength', '?')} chars after stripping "
            "— longer codes are truncated in LimeSurvey, so short codes (or plain integers, "
            "as in the examples) are safest.\n"
            "- Labels/hints carry the human text; keep names/codes machine-stable.\n"
        )

    # Choice sheet
    out.append("## Choices sheet\n")
    out.append(
        "`select_one` / `select_multiple` rows reference a `list_name`. Define options on "
        "the `choices` sheet with columns `list_name`, `name` (code), `label`. Every "
        "`list_name` used on the survey sheet must exist on the choices sheet.\n"
    )

    # or_other
    if other:
        out.append("## `or_other` pattern (open “Other” field)\n")
        out.append(
            f"Applies to: {', '.join(f'`{t}`' for t in other.get('appliesTo', []))}. "
            f"Add a choice with code `{other.get('choiceCode', 'other')}`, then a companion "
            f"row of type `{other.get('companionType', 'text')}` named "
            f"`<question>{other.get('companionSuffix', '_other')}` shown only when the "
            "“other” choice is picked — set its `relevant` to `${<question>} = "
            f"'{other.get('choiceCode', 'other')}'`. See the `select_one_other` example.\n"
        )

    # External code list / long list
    if ext:
        out.append("## Long lists from a file (`select_*_from_file`)\n")
        # Example filename comes from the registry, not a hardcoded vocabulary:
        # vocabularies are open-ended (convention:externalCodeList's
        # vocabularyDeclaration), so the skill doc must not pin one.
        example_file = vocabs[0].get("xlsformFilename", "<name>.csv") if vocabs else "<name>.csv"
        out.append(
            f"Type pattern: `{ext.get('xlsformTypePattern', '')}` — e.g. "
            f"`select_one_from_file {example_file}`. Use for long, standardised controlled "
            "vocabularies instead of hundreds of inline choices. Registered vocabularies:\n"
        )
        if vocabs:
            out.append("\n| File | Vocabulary | Standard |")
            out.append("|---|---|---|")
            for v in vocabs:
                out.append(
                    f"| `{v.get('xlsformFilename', '')}` | {v.get('skos:prefLabel', '')} | {v.get('standard', '—')} |"
                )
            out.append("")

    # Logic
    if logic:
        out.append("## Skip logic & validation (`relevant`, `constraint`)\n")
        out.append(
            "Written in the XLSForm XPath subset. `${name}` references another answer; "
            "`.` (in `constraint`) refers to this answer; `selected(${q}, 'code')` tests a "
            "choice. `constraint_message` holds the plain-text error.\n"
        )
        fns = logic.get("supportedXPathFunctions", [])
        if fns:
            out.append(
                "\n**Only these functions are supported** (anything else is rejected):\n\n"
                + ", ".join(f"`{f}`" for f in fns)
                + "\n"
            )

    # Appearances
    if appearances:
        out.append("## Appearances (`appearance` column)\n")
        out.append("| `appearance` | Meaning | Valid on |")
        out.append("|---|---|---|")
        for a in appearances:
            valid = ", ".join(f"`{t}`" for t in a.get("validForTypes", []))
            out.append(f"| `{a['xlsform']['appearanceString']}` | {a.get('skos:prefLabel', '')} | {valid} |")
        out.append("")

    # Language
    if lang:
        out.append("## Multi-language\n")
        out.append(
            "Add per-language columns `label::<lang>`, `hint::<lang>`, etc., where `<lang>` "
            "is an IETF BCP-47 tag (`de`, `en`, `fr-BE`). Set `default_language` on the "
            "`settings` sheet.\n"
        )

    # Settings
    if settings:
        out.append("## `settings` sheet\n")
        out.append("| Key | Required |")
        out.append("|---|---|")
        for f in settings.get("fields", []):
            out.append(f"| `{f.get('xlsformKey', '')}` | {'yes' if f.get('required') else 'no'} |")
        out.append("")
        magic = settings.get("magicNames", [])
        if magic:
            out.append("**Conventional magic rows:**\n")
            for m in magic:
                out.append(f"- {m.get('xlsformRow', '')} → {m.get('note', '')}")
            out.append("")

    return "\n".join(out) + "\n"


def generate_skill(registry: dict[str, Any], base_dir: Path, skill_root: Path) -> int:
    """Write the cdl-survey-types sub-skill under `skill_root`. Returns file count."""
    refs = skill_root / "references"
    refs.mkdir(parents=True, exist_ok=True)

    (skill_root / "SKILL.md").write_text(_skill_md(registry))
    (refs / "question-types.md").write_text(_question_types_md(registry, base_dir))
    (refs / "xlsform-syntax.md").write_text(_syntax_md(registry))
    return 3
