"""Generators that emit TypeScript / JSON artifacts consumed by the in-repo transformer."""

import json
from collections import OrderedDict
from pathlib import Path
from typing import Any

from .predicates import _is_ddi_emittable
from .util import _slug, _ts_key


def generate_typescript(registry: dict[str, Any], output: Path):
    """Generate TypeScript type mappings for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " */",
        "",
        "export type TypeKind = 'question' | 'metadata' | 'structural';",
        "",
        "export interface TypeMapping {",
        "  kind: TypeKind;",
        "  limeSurveyType: string | null;",
        "  supported: boolean;",
        "  supportsOther?: boolean;",
        "  answerClass?: 'A' | 'SQ' | null;",
        "  requiresListName?: boolean;",
        "  dateFormat?: string;",
        "}",
        "",
        "export const TYPE_MAPPINGS: Record<string, TypeMapping> = {",
    ]

    def emit(name: str, kind: str, data: dict):
        ls = data.get("limesurvey", {})
        xls = data.get("xlsform", {})
        supported = ls.get("supported", True) if ls else True
        # If typeCode missing and not explicitly supported=true, treat as unsupported
        if ls.get("typeCode") is None and "supported" not in ls:
            supported = False
        lines.append(f"  {_ts_key(name)}: {{")
        lines.append(f"    kind: {json.dumps(kind)},")
        lines.append(f"    limeSurveyType: {json.dumps(ls.get('typeCode'))},")
        lines.append(f"    supported: {'true' if supported else 'false'},")
        if ls.get("supportsOther"):
            lines.append("    supportsOther: true,")
        if ls.get("answerClass"):
            lines.append(f"    answerClass: {json.dumps(ls['answerClass'])},")
        if xls.get("requiresListName"):
            lines.append("    requiresListName: true,")
        if ls.get("dateFormat"):
            lines.append(f"    dateFormat: {json.dumps(ls['dateFormat'])},")
        lines.append("  },")

    kind_map = {
        "QuestionType": "question",
        "StructuralType": "structural",
    }
    for _type_id, data in registry.items():
        kind = kind_map.get(data.get("@type"))
        if kind is None:
            continue
        xlsform = data["xlsform"]["typeString"]
        emit(xlsform, kind, data)
        for alias in data["xlsform"].get("aliases", []):
            emit(alias, kind, data)

    lines.append("};")
    lines.append("")

    output.write_text("\n".join(lines))


def generate_typescript_ddi(registry: dict[str, Any], output: Path):  # noqa: C901 (grandfathered; split before extending)
    """Generate TypeScript DDI-Codebook mappings for the DDI emitter (src/ddi/).

    Mirrors generate_python's DDI section: same registry-derived maps, emitted
    as a TS module the in-repo emitter imports. Registry is the single source
    of truth for what maps to what.
    """
    L: list[str] = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " *",
        " * DDI-Codebook 2.5 type mappings consumed by the DDI emitter (src/ddi/).",
        " */",
        "",
        "/** DDI interval classification + varFormat type for a standardized type. */",
        "export type DdiTypeInfo = readonly [intrvl: string, formatType: string];",
        "",
        "/** External code-list vocabulary metadata (long-list pattern). */",
        "export interface Vocabulary {",
        "  ddiVocab: string;",
        "  vocabURI: string;",
        "  standard: string;",
        "  label: string;",
        "}",
        "",
        "/** XLSForm type string → standardized type slug. */",
        "export const TYPE_MAP: Record<string, string> = {",
    ]

    for type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        xlsform = data["xlsform"]["typeString"]
        canon = _slug(type_id)
        L.append(f"  {_ts_key(xlsform)}: {json.dumps(canon)},")
        for alias in data["xlsform"].get("aliases", []):
            L.append(f"  {_ts_key(alias)}: {json.dumps(canon)},")
    L.append("};")
    L.append("")

    L.append("/** XLSForm types with no DDI interval — not emitted as <var> (no ddi.intrvl). */")
    L.append("export const NON_DDI_EMITTABLE_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        if not data.get("ddi", {}).get("intrvl"):
            L.append(f"  {json.dumps(data['xlsform']['typeString'])},")
    L.append("];")
    L.append("")

    L.append("/** XLSForm structural types (begin_group / end_group). */")
    L.append("export const STRUCTURAL_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "StructuralType":
            continue
        xls = data.get("xlsform", {}).get("typeString")
        if xls:
            L.append(f"  {json.dumps(xls)},")
    L.append("];")
    L.append("")

    L.append("/** Standardized type → [intrvl, formatType]. Only DDI-emittable types. */")
    L.append("export const DDI_TYPE_MAP: Record<string, DdiTypeInfo> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        ddi = data["ddi"]
        intrvl = ddi.get("intrvl", "discrete")
        fmt_type = ddi.get("formatType", "character")
        L.append(f"  {_ts_key(_slug(type_id))}: [{json.dumps(intrvl)}, {json.dumps(fmt_type)}],")
    L.append("};")
    L.append("")

    L.append("/** Standardized type → responseDomainType for <qstn>. */")
    L.append("export const RESPONSE_DOMAIN_MAP: Record<string, string> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        rd = data["ddi"].get("responseDomainType")
        if rd:
            L.append(f"  {_ts_key(_slug(type_id))}: {json.dumps(rd)},")
    L.append("};")
    L.append("")

    L.append("/** Standardized type → measurement level. */")
    L.append("export const MEASURE_MAP: Record<string, string> = {")
    for type_id, data in registry.items():
        if not _is_ddi_emittable(data):
            continue
        ddi = data.get("ddi", {})
        intrvl = ddi.get("intrvl", "")
        xls = data["xlsform"]["typeString"]
        if intrvl == "nominal" or (
            intrvl == "discrete"
            and xls in ["select_one", "select_multiple", "select_one_from_file", "select_multiple_from_file"]
        ):
            measure = "nominal"
        elif intrvl == "ordinal" or xls == "rank":
            measure = "ordinal"
        elif xls in ("date", "time") or intrvl == "interval":
            measure = "interval"
        elif intrvl == "contin":
            measure = "ratio"
        else:
            continue
        L.append(f"  {_ts_key(_slug(type_id))}: {json.dumps(measure)},")
    L.append("};")
    L.append("")

    L.append("/** External code-list vocabularies, keyed by xlsform filename. */")
    L.append("export const VOCABULARIES: Record<string, Vocabulary> = {")
    for _type_id, data in registry.items():
        if data.get("@type") != "Vocabulary":
            continue
        fn = data.get("xlsformFilename")
        if not fn:
            continue
        L.append(f"  {_ts_key(fn)}: {{")
        L.append(f"    ddiVocab: {json.dumps(data.get('ddiVocab', ''))},")
        L.append(f"    vocabURI: {json.dumps(data.get('vocabURI', ''))},")
        L.append(f"    standard: {json.dumps(data.get('standard', ''))},")
        L.append(f"    label: {json.dumps(data.get('skos:prefLabel', ''))},")
        L.append("  },")
    L.append("};")
    L.append("")

    L.append("/** XLSForm types sourcing choices from an external file (emit <concept vocab>). */")
    L.append("export const EXTERNAL_CODELIST_TYPES: readonly string[] = [")
    for _type_id, data in registry.items():
        if data.get("@type") != "QuestionType":
            continue
        if data.get("ddi", {}).get("externalCodeList"):
            L.append(f"  {json.dumps(data['xlsform']['typeString'])},")
    L.append("];")
    L.append("")

    output.write_text("\n".join(L))


def generate_appearances(registry: dict[str, Any], output: Path):
    """Emit Appearance entries as TS map for xlsform2lstsv."""
    lines = [
        "/**",
        " * GENERATED CODE - DO NOT EDIT",
        " * Source: registry/root.jsonld",
        " * Generated by: codegen",
        " */",
        "",
        "export interface AppearanceSpec {",
        "  supported: boolean;",
        "  behavior: 'handled' | 'warn';",
        "  validForTypes?: string[];",
        "  lsEffect: string;",
        "  lsTypeOverride?: string;",
        "  /** False when a row bearing this appearance stores no response (matrix header). */",
        "  carriesData?: boolean;",
        "}",
        "",
        "export const APPEARANCES: Record<string, AppearanceSpec> = {",
    ]
    # Build alias map: typeString -> [typeString, ...aliases]
    alias_map: dict[str, list[str]] = {}
    for data in registry.values():
        if data.get("@type") != "QuestionType":
            continue
        xls = data.get("xlsform", {})
        primary = xls.get("typeString")
        if not primary:
            continue
        alias_map[primary] = [primary, *list(xls.get("aliases", []))]

    def expand_types(types: list[str]) -> list[str]:
        out: list[str] = []
        seen: set[str] = set()
        for t in types:
            for x in alias_map.get(t, [t]):
                if x not in seen:
                    seen.add(x)
                    out.append(x)
        return out

    for _type_id, data in registry.items():
        if data.get("@type") != "Appearance":
            continue
        aid = data["xlsform"]["appearanceString"]
        lines.append(f"  {json.dumps(aid)}: {{")
        lines.append(f"    supported: {'true' if data['supported'] else 'false'},")
        lines.append(f"    behavior: {json.dumps(data['behavior'])},")
        if data.get("validForTypes"):
            expanded = expand_types(data["validForTypes"])
            lines.append(f"    validForTypes: {json.dumps(expanded)},")
        lines.append(f"    lsEffect: {json.dumps(data['lsEffect'])},")
        if data.get("lsTypeOverride"):
            lines.append(f"    lsTypeOverride: {json.dumps(data['lsTypeOverride'])},")
        # Only emitted when explicitly false — absence means "carries data".
        if data.get("carriesData") is False:
            lines.append("    carriesData: false,")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    output.write_text("\n".join(lines))


def generate_conventions(registry: dict[str, Any], output: Path):
    """Emit global conventions + column map + composites as JSON."""
    conv = {}
    col_map = []
    composites = []
    for _type_id, data in registry.items():
        t = data.get("@type")
        if t == "GlobalConvention":
            slug = data["@id"].split(":", 1)[1]
            conv[slug] = data.get("rule", {})
        elif t == "XLSFormColumnMap":
            col_map = data.get("map", [])
        elif t == "Composite":
            composites.append(
                OrderedDict(
                    [
                        ("id", data["@id"].split(":", 1)[1]),
                        ("label", data.get("skos:prefLabel")),
                        ("broader", data.get("skos:broader")),
                        ("trigger", data.get("trigger", {})),
                        ("input", data.get("input", {})),
                        ("output", data.get("output", {})),
                        ("schematronPatterns", data.get("schematronPatterns", [])),
                        ("notes", data.get("notes", [])),
                    ]
                )
            )
    # Sort so output is independent of registry file layout (conventions now
    # live in separate conventions/*.jsonld files loaded by glob).
    conv = {k: conv[k] for k in sorted(conv)}
    composites.sort(key=lambda c: c["id"])
    out = {
        "$comment": "GENERATED - DO NOT EDIT. Source: registry/root.jsonld",
        "conventions": conv,
        "xlsformColumnMap": col_map,
        "composites": composites,
    }
    output.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
