"""Generate a self-contained Claude Code sub-skill from the registry.

The registry is the single source of truth for which answer types exist and what
XLSForm syntax is allowed. This emitter renders that into a nested skill
(`skills/cdl-survey-types/`) that a parent survey-generator skill (formulaid's
`generating-xlsforms`) includes: the parent owns the workflow (intake, qwac
search, delivery); this sub-skill owns the authoritative "which type + how to
write it in XLSForm" reference.

Output layout (mirrors formulaid's own SKILL.md + references/ shape):

    skills/cdl-survey-types/
      SKILL.md                       frontmatter + pick-a-type table + index
      references/question-types.md   per-type detail, variants, worked examples
      references/xlsform-syntax.md    naming, or_other, logic, appearances, settings

Everything below the frontmatter is derived — re-running codegen overwrites it.
"""

import json
import re
from pathlib import Path
from typing import Any

SKILL_NAME = "cdl-survey-types"

_DO_NOT_EDIT = (
    "<!-- GENERATED by codegen (codegen/emit_skill.py) from the formtransform registry. "
    "DO NOT EDIT BY HAND — edit registry/ and re-run `uv run codegen`. -->\n"
)


def _tidy(md: str) -> str:
    """Collapse runs of blank lines and end with exactly one newline.

    The emitters below build markdown by appending blocks that each carry their own
    trailing newline, which leaves double blank lines at the seams (markdownlint
    MD012). Normalising once here keeps every emitter free of blank-line bookkeeping.
    """
    return re.sub(r"\n{3,}", "\n\n", md).rstrip("\n") + "\n"


def _load_example(base_dir: Path, entry: dict[str, Any]) -> dict[str, Any] | None:
    """Read an entity's xlsform.json worked example, if it has one on disk."""
    ex = entry.get("examplePath") or (f"{entry['exampleDir']}/xlsform.json" if entry.get("exampleDir") else None)
    if not ex:
        return None
    path = base_dir / ex
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def _fmt_example(example: dict[str, Any]) -> str:
    """Compact JSON block of an xlsform.json fixture (survey + choices)."""
    trimmed = {k: example[k] for k in ("survey", "choices") if example.get(k)}
    return "```json\n" + json.dumps(trimmed, indent=2, ensure_ascii=False) + "\n```"


def _skill_md(registry: dict[str, Any]) -> str:
    """SKILL.md — frontmatter + the pick-a-type table (useWhen) + index."""
    qtypes = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionType"),
        key=lambda d: d["xlsform"]["typeString"],
    )
    variants = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionTypeVariant"),
        key=lambda d: d["@id"],
    )
    composites = sorted(
        (d for d in registry.values() if d.get("@type") == "Composite"),
        key=lambda d: d["@id"],
    )

    rows = ["| XLSForm `type` | Name | Use when |", "|---|---|---|"]
    for d in qtypes:
        ts = d["xlsform"]["typeString"]
        rows.append(f"| `{ts}` | {d.get('skos:prefLabel', ts)} | {d.get('useWhen', '—')} |")

    vrows = ["| Variant | Base | Use when |", "|---|---|---|"]
    for d in variants:
        base = d.get("skos:broader", {})
        base_id = base.get("@id", "") if isinstance(base, dict) else ""
        base_slug = base_id.split(":", 1)[1] if ":" in base_id else base_id
        vrows.append(f"| `{d['@id'].split(':', 1)[1]}` | `{base_slug}` | {d.get('useWhen', '—')} |")

    crows = ["| Composite | Use when |", "|---|---|"]
    for d in composites:
        crows.append(f"| `{d['@id'].split(':', 1)[1]}` | {d.get('useWhen', '—')} |")

    desc = (
        "The authoritative catalogue of survey answer types and the XLSForm syntax "
        "allowed by the CDL survey pipeline (formtransform). Include this "
        "sub-skill from a survey-generator skill to pick the right question type and "
        "emit valid XLSForm. The registry is an allowlist: any type not listed here is "
        "rejected downstream."
    )

    return (
        "---\n"
        f"name: {SKILL_NAME}\n"
        f'description: "{desc}"\n'
        "---\n\n"
        f"{_DO_NOT_EDIT}\n"
        "# CDL Survey Answer Types & XLSForm Syntax\n\n"
        "Generated from the [`formtransform`](https://github.com/) — the single "
        "source of truth for the CDL survey pipeline (XLSForm → LimeSurvey TSV / DDI). "
        "**This is an allowlist.** Only the types below are valid; any other survey-sheet "
        "`type` aborts the transformation.\n\n"
        "## Pick a question type\n\n"
        + "\n".join(rows)
        + "\n\n### Variants (a base type under a presentation modifier)\n\n"
        + "\n".join(vrows)
        + "\n\n### Composites (one question spanning several rows)\n\n"
        + "\n".join(crows)
        + "\n\n## References\n\n"
        "| File | Contents |\n"
        "|------|----------|\n"
        "| [references/question-types.md](references/question-types.md) | "
        "Per-type detail: XLSForm `type` string, constraints, variants, worked example. |\n"
        "| [references/xlsform-syntax.md](references/xlsform-syntax.md) | "
        "Allowed XLSForm syntax: naming rules, choice sheet, `or_other`, skip/validation "
        "logic, appearances, `settings` sheet, metadata rows. |\n\n"
        "Read both reference files before emitting XLSForm.\n"
    )


def _variants_by_base(registry: dict[str, Any]) -> dict[str, list[dict]]:
    """Variant entries grouped by the `@id` of the base type they narrow."""
    grouped: dict[str, list[dict]] = {}
    for d in registry.values():
        if d.get("@type") != "QuestionTypeVariant":
            continue
        base = d.get("skos:broader", {})
        base_id = base.get("@id", "") if isinstance(base, dict) else ""
        grouped.setdefault(base_id, []).append(d)
    return grouped


def _constraint_lines(constraints: dict[str, Any]) -> list[str]:
    """Constraints paragraph + warning blockquote for one type."""
    out: list[str] = []
    cl = []
    if "maxNameLength" in constraints:
        cl.append(
            f"variable `name` \u2264 {constraints['maxNameLength']} chars, `{constraints.get('namePattern', '')}`"
        )
    if "maxChoiceCodeLength" in constraints:
        cl.append(
            f"choice code \u2264 {constraints['maxChoiceCodeLength']} chars, "
            f"`{constraints.get('choiceCodePattern', '')}`"
        )
    if cl:
        out.append("**Constraints:** " + "; ".join(cl) + "\n")
    warnings = constraints.get("warnings", [])
    if warnings:
        # One blockquote, `>`-joined: separate quotes with a blank line between them
        # would be two blockquotes (markdownlint MD028).
        out.append("\n>\n".join(f"> \u26a0\ufe0f {w}" for w in warnings) + "\n")
    return out


def _type_section(d: dict[str, Any], variants: list[dict], base_dir: Path) -> list[str]:
    """The `## <type>` block: header, use-when, aliases, constraints, variants, examples."""
    ts = d["xlsform"]["typeString"]
    out = [
        f"## `{ts}` \u2014 {d.get('skos:prefLabel', ts)}\n",
        f"**Use when:** {d.get('useWhen', '\u2014')}\n",
    ]

    aliases = d["xlsform"].get("aliases")
    if aliases:
        out.append(f"**Accepted aliases:** {', '.join(f'`{a}`' for a in aliases)}\n")
    if d.get("ddi", {}).get("externalCodeList"):
        out.append(
            "**Requires a registered vocabulary:** write the type cell as "
            f"`{ts} <file>.csv` with a file from the registered-vocabularies table in "
            "[xlsform-syntax.md](xlsform-syntax.md). The options come from that "
            "vocabulary; add no rows to the `choices` sheet.\n"
        )
    elif d["xlsform"].get("requiresListName"):
        out.append(
            "**Requires a choice list:** write the type cell as "
            f"`{ts} <list_name>` and define the options on the `choices` sheet under "
            "that `list_name`.\n"
        )

    out += _constraint_lines(d.get("constraints", {}))

    vs = sorted(variants, key=lambda x: x["@id"])
    if vs:
        out.append("**Variants:**\n")
        for v in vs:
            out.append(
                f"- `{v['@id'].split(':', 1)[1]}` \u2014 {v.get('skos:prefLabel', '')}: {v.get('useWhen', '\u2014')}"
            )
        out.append("")

    example = _load_example(base_dir, d)
    if example:
        out.append("**Example:**\n")
        out.append(_fmt_example(example) + "\n")

    # Worked examples for this type's variants (e.g. the _other companion row).
    for v in vs:
        vex = _load_example(base_dir, v)
        if vex:
            out.append(f"**Example \u2014 `{v['@id'].split(':', 1)[1]}`:**\n")
            out.append(_fmt_example(vex) + "\n")

    return out


def _question_types_md(registry: dict[str, Any], base_dir: Path) -> str:
    qtypes = sorted(
        (d for d in registry.values() if d.get("@type") == "QuestionType"),
        key=lambda d: d["xlsform"]["typeString"],
    )
    variants_by_base = _variants_by_base(registry)

    out = [_DO_NOT_EDIT, "# Question Types (detail)\n"]
    for d in qtypes:
        out += _type_section(d, variants_by_base.get(d["@id"], []), base_dir)

    return _tidy("\n".join(out))


def _naming_section(san: dict) -> list[str]:
    n = san.get("name", {})
    cc = san.get("choiceCode", {})
    return [
        "## Names & choice codes\n",
        f"Write names and choice codes as letters and digits only (`{n.get('pattern', '')}`), "
        "e.g. `jobsatisfaction` or `jobSatisfaction`: no underscores, hyphens, spaces "
        "or umlauts. The only exception is the `<question>_other` companion row. "
        "The validator rejects anything else. `FieldSanitizer` produces conforming "
        "names from free text: it transliterates (`ä`→`ae`, `ß`→`ss`), drops other "
        "diacritics, deletes the remaining non-alphanumerics and truncates, so keep "
        "the stem short and unambiguous:\n",
        f"- **Variable `name`:** \u2264 {n.get('maxLength', '?')} chars after stripping. "
        "Must be unique \u2014 duplicates get a numeric suffix.",
        f"- **Choice `name` (code):** \u2264 {cc.get('maxLength', '?')} chars after stripping "
        "\u2014 longer codes are truncated in LimeSurvey, so short codes (or plain integers, "
        "as in the examples) are safest.",
        "- Labels/hints carry the human text; keep names/codes machine-stable.\n",
    ]


def _allowlist_section(unreg: dict) -> list[str]:
    meta_rows = ", ".join(f"`{r}`" for r in unreg.get("metadataRowTypes", []))
    return [
        "## Row types are an allowlist\n",
        f"{unreg.get('unknownTypeBehavior', '')}\n\n"
        f"Metadata rows ({meta_rows}) are accepted and carried but produce no authored "
        "question. Every other `type` must be one of the registered question / structural "
        "types.\n",
    ]


def _other_section(other: dict) -> list[str]:
    code = other.get("choiceCode", "other")
    return [
        "## `or_other` pattern (open \u201cOther\u201d field)\n",
        f"Applies to: {', '.join(f'`{t}`' for t in other.get('appliesTo', []))}. "
        f"Add a choice with code `{code}`, then a companion "
        f"row of type `{other.get('companionType', 'text')}` named "
        f"`<question>{other.get('companionSuffix', '_other')}` shown only when the "
        "\u201cother\u201d choice is picked \u2014 set its `relevant` to `${<question>} = "
        f"'{code}'`. See the `select_one_other` example.\n",
    ]


def _exclusive_section(ex: dict) -> list[str]:
    col = ex.get("choicesColumn", "exclusive")
    yes = ex.get("trueValues", ["yes"])[0]
    applies = ", ".join(f"`{t}`" for t in ex.get("appliesTo", []))
    return [
        "## Exclusive answers (`exclusive` column)\n",
        f"Applies to: {applies}. For an answer that rules out all others "
        "(\u201cKeine Angabe\u201d, \u201cNichts davon\u201d, \u201cWei\u00df nicht\u201d), "
        f"add the `{col}` column to the `choices` sheet and set it to `{yes}` on that "
        "choice. Leave it empty on every other row. Don't write a `count-selected()` "
        "constraint for this; it isn't converted.\n",
    ]


def _external_list_section(ext: dict, vocabs: list[dict]) -> list[str]:
    # Example filename comes from the registry, not a hardcoded vocabulary:
    # vocabularies are open-ended (convention:externalCodeList's
    # vocabularyDeclaration), so the skill doc must not pin one.
    example_file = vocabs[0].get("xlsformFilename", "<name>.csv") if vocabs else "<name>.csv"
    out = [
        "## Long lists from a file (`select_*_from_file`)\n",
        f"Type pattern: `{ext.get('xlsformTypePattern', '')}` \u2014 e.g. "
        f"`select_one_from_file {example_file}`. Use for long, standardised controlled "
        "vocabularies instead of hundreds of inline choices. Registered vocabularies:\n",
    ]
    if vocabs:
        out.append("| File | Vocabulary | Standard |")
        out.append("|---|---|---|")
        for v in vocabs:
            out.append(
                f"| `{v.get('xlsformFilename', '')}` | {v.get('skos:prefLabel', '')} | {v.get('standard', '\u2014')} |"
            )
        out.append("")
    return out


def _logic_section(logic: dict) -> list[str]:
    out = [
        "## Skip logic & validation (`relevant`, `constraint`)\n",
        "Written in the XLSForm XPath subset. `${name}` references another answer; "
        "`.` (in `constraint`) refers to this answer; `selected(${q}, 'code')` tests a "
        "choice. `constraint_message` holds the plain-text error.\n",
    ]
    fns = logic.get("supportedXPathFunctions", [])
    if fns:
        out.append(
            "**Only these functions are supported** (anything else is rejected):\n\n"
            + ", ".join(f"`{f}`" for f in fns)
            + "\n"
        )
    return out


def _appearances_section(appearances: list[dict]) -> list[str]:
    out = ["## Appearances (`appearance` column)\n", "| `appearance` | Meaning | Valid on |", "|---|---|---|"]
    for a in appearances:
        valid = ", ".join(f"`{t}`" for t in a.get("validForTypes", []))
        out.append(f"| `{a['xlsform']['appearanceString']}` | {a.get('skos:prefLabel', '')} | {valid} |")
    out.append("")
    return out


def _settings_section(settings: dict) -> list[str]:
    out = ["## `settings` sheet\n", "| Key | Required |", "|---|---|"]
    for f in settings.get("fields", []):
        out.append(f"| `{f.get('xlsformKey', '')}` | {'yes' if f.get('required') else 'no'} |")
    out.append("")
    magic = settings.get("magicNames", [])
    if magic:
        out.append("**Conventional magic rows:**\n")
        for m in magic:
            out.append(f"- {m.get('xlsformRow', '')} \u2192 {m.get('note', '')}")
        out.append("")
    return out


_LANGUAGE_SECTION = [
    "## Multi-language\n",
    "Add per-language columns `label::<lang>`, `hint::<lang>`, etc., where `<lang>` "
    "is an IETF BCP-47 tag (`de`, `en`, `fr-BE`). Set `default_language` on the "
    "`settings` sheet.\n",
]

_CHOICES_SECTION = [
    "## Choices sheet\n",
    "`select_one` / `select_multiple` rows reference a `list_name`. Define options on "
    "the `choices` sheet with columns `list_name`, `name` (code), `label`. Every "
    "`list_name` used on the survey sheet must exist on the choices sheet.\n",
]


def _syntax_md(registry: dict[str, Any]) -> str:
    def conv(cid: str) -> dict:
        return registry.get(cid, {}).get("rule", {})

    appearances = sorted(
        (d for d in registry.values() if d.get("@type") == "Appearance"),
        key=lambda d: d["xlsform"]["appearanceString"],
    )
    vocabs = sorted(
        (d for d in registry.values() if d.get("@type") == "Vocabulary"),
        key=lambda d: d.get("xlsformFilename", ""),
    )

    # (rule, section builder) in document order; a missing rule drops its section.
    sections: list[tuple[Any, Any]] = [
        (conv("convention:unregisteredRows"), _allowlist_section),
        (conv("convention:sanitization"), _naming_section),
        (True, lambda _: _CHOICES_SECTION),
        (conv("convention:other"), _other_section),
        (conv("convention:exclusiveChoice"), _exclusive_section),
        (conv("convention:externalCodeList"), lambda ext: _external_list_section(ext, vocabs)),
        (conv("convention:logicMapping"), _logic_section),
        (appearances, lambda _: _appearances_section(appearances)),
        (conv("convention:languageTagging"), lambda _: _LANGUAGE_SECTION),
        (conv("convention:surveySettings"), _settings_section),
    ]

    out = [_DO_NOT_EDIT, "# Allowed XLSForm Syntax\n"]
    for rule, build in sections:
        if rule:
            out += build(rule)

    return _tidy("\n".join(out))


def generate_skill(registry: dict[str, Any], base_dir: Path, skill_root: Path) -> int:
    """Write the cdl-survey-types sub-skill under `skill_root`. Returns file count."""
    refs = skill_root / "references"
    refs.mkdir(parents=True, exist_ok=True)

    (skill_root / "SKILL.md").write_text(_skill_md(registry))
    (refs / "question-types.md").write_text(_question_types_md(registry, base_dir))
    (refs / "xlsform-syntax.md").write_text(_syntax_md(registry))
    return 3
