"""Generators that emit human-readable Markdown documentation from the registry."""

from pathlib import Path
from typing import Any


def generate_type_docs(registry: dict[str, Any], base_dir: Path) -> int:
    """For each type that has a registry/entities/<slug>/ folder on disk, write
    registry/entities/<slug>/docs.md with workflow narrative + lifecycle mermaid.

    Returns count written.
    """
    typed_entries = [e for e in registry.values() if e.get("@type") in ("QuestionType", "StructuralType")]

    # Build lookup: QuestionTypeVariant by @id for variants[] resolution
    variants_by_id = {e["@id"]: e for e in registry.values() if e.get("@type") == "QuestionTypeVariant"}

    written = 0
    for entry in typed_entries:
        slug = entry["xlsform"]["typeString"]
        tdir = base_dir / "registry" / "entities" / slug
        if not tdir.exists():
            continue

        label = entry.get("skos:prefLabel", slug)
        use_when = entry.get("useWhen", "")
        ls_code = entry.get("limesurvey", {}).get("typeCode") or "—"
        intrvl = entry.get("ddi", {}).get("intrvl", "—")
        rd = entry.get("ddi", {}).get("responseDomainType", "—")
        fmt_type = entry.get("ddi", {}).get("formatType", "—")
        constraints = entry.get("constraints", {})

        # Variant table
        variant_rows: list[str] = []
        for vid in entry.get("variants", []):
            v = variants_by_id.get(vid)
            if not v:
                continue
            vslug = vid.split(":", 1)[1]
            vlabel = v.get("skos:prefLabel", vslug)
            pres = v.get("presentation", {})
            flags: list[str] = []
            if pres.get("withOther"):
                flags.append("`or_other`")
            if pres.get("withLongList"):
                flags.append("external file")
            if pres.get("appearanceString"):
                flags.append(f"appearance={pres['appearanceString']}")
            flag_str = ", ".join(flags) or "—"
            v_use_when = v.get("useWhen", "—")
            variant_rows.append(f"| [`{vslug}`](../{vslug}/) | {vlabel} | {flag_str} | {v_use_when} |")

        variant_block = (
            (
                "## Variants\n\n| ID | Label | Notes | Use when |\n|----|-------|-------|----------|\n"
                + "\n".join(variant_rows)
                + "\n\n"
            )
            if variant_rows
            else ""
        )

        constraint_lines = []
        if "maxNameLength" in constraints:
            constraint_lines.append(
                f"- Variable name ≤ {constraints['maxNameLength']} chars, "
                f"pattern `{constraints.get('namePattern', '?')}`"
            )
        if "maxChoiceCodeLength" in constraints:
            constraint_lines.append(
                f"- Choice code ≤ {constraints['maxChoiceCodeLength']} chars, "
                f"pattern `{constraints.get('choiceCodePattern', '?')}` "
                f"(truncated in LimeSurvey, prefix collisions warned)"
            )
        for w in constraints.get("warnings", []):
            constraint_lines.append(f"- ⚠️ {w}")
        constraint_block = "\n".join(constraint_lines) if constraint_lines else "_None._"

        # Lifecycle Mermaid
        mermaid = f"""```mermaid
graph LR
    XLS["XLSForm row<br/>type: {slug}"]
    LS["LS TSV<br/>type/scale: {ls_code}"]
    DDI["DDI XML<br/>&lt;var intrvl={intrvl}<br/>responseDomainType={rd}&gt;"]
    XLS -->|xlsform2lstsv| LS
    LS -->|lstsv2xlsform| XLS
    XLS -->|xlsform2ddi| DDI
    LS -->|lstsv2ddi| DDI
```

DDI is the terminus: it describes the dataset, not the instrument, so there is no
path back out of it (see `src/pipelines/README.md`)."""

        doc = f"""<!-- GENERATED by codegen — DO NOT EDIT BY HAND.
     Edit `registry/entities/{slug}/definition.jsonld` and re-run `uv run codegen`. -->

# {label} (`{slug}`)

## Use when

{use_when or "_Not specified._"}

## Cross-format mapping

| Format | Value |
|--------|-------|
| XLSForm typeString | `{slug}` |
| LimeSurvey type code | `{ls_code}` |
| DDI `intrvl` | `{intrvl}` |
| DDI `responseDomainType` | `{rd}` |
| DDI `varFormat/@type` | `{fmt_type}` |

## Lifecycle across the ecosystem

{mermaid}

{variant_block}## Constraints

{constraint_block}

## Tests

- `src/test/registryConformance.test.ts` (XLSForm → LS TSV contract + tsv.tsv snapshots, vitest)
- `src/test/ddi/` (XLSForm → DDI emitter unit tests + ddi.xml snapshots, vitest)
- `tests/validation/test_ddi_schema.py` (XSD + schematron over blessed snapshots)

## Source

- [`definition.jsonld`](definition.jsonld) — the QuestionType entry (single source for codegen)
- `fixtures/xlsform.json` — this type's example input
- `generated/` — codegen outputs (docs.md, xlsform.xlsx)
- `ddi.xml` / `tsv.tsv` — blessed snapshots
- `../<variant>/` — sibling folders for each real variant (e.g. `_other`, `_long_list`)
"""
        (tdir / "generated").mkdir(exist_ok=True)
        (tdir / "generated" / "docs.md").write_text(doc)
        written += 1
    return written
