<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by codegen — DO NOT EDIT BY HAND.
     Edit registry/root.jsonld (+ registry/entities/<slug>/definition.jsonld) and re-run `uv run codegen`. -->
<schema xmlns="http://purl.oclc.org/dsdl/schematron" queryBinding="xpath2">
    <ns prefix="ddi" uri="ddi:codebook:2_5"/>

    <pattern id="uniqueness">
    <rule context="ddi:var">
        <assert test="not(preceding::ddi:var/@ID = @ID)">Duplicate Variable ID found: <value-of select="@ID"/></assert>
    </rule>
    <rule context="ddi:varGrp">
        <assert test="not(preceding::ddi:varGrp/@ID = @ID)">Duplicate Variable Group ID found: <value-of select="@ID"/></assert>
    </rule>
    <rule context="var">
        <assert test="not(preceding::var/@ID = @ID)">Duplicate Variable ID found: <value-of select="@ID"/></assert>
    </rule>
    <rule context="varGrp">
        <assert test="not(preceding::varGrp/@ID = @ID)">Duplicate Variable Group ID found: <value-of select="@ID"/></assert>
    </rule>
    </pattern>

    <pattern id="essentials">
    <!-- Variable essentials -->
    <rule context="ddi:var">
        <assert test="@name">Variable <value-of select="@ID"/> is missing a name attribute.</assert>
        <assert test="@intrvl">Variable <value-of select="@name"/> is missing an intrvl attribute (use "discrete" or "contin").</assert>
        <assert test="ddi:qstn/@responseDomainType">Variable <value-of select="@name"/> is missing responseDomainType on qstn.</assert>
        <assert test="ddi:qstn/ddi:qstnLit">Variable <value-of select="@name"/> is missing a question literal (qstnLit).</assert>
        <assert test="ddi:varFormat">Variable <value-of select="@name"/> is missing technical format (varFormat).</assert>
        <assert test="ddi:concept[normalize-space(.) != '']">Variable <value-of select="@name"/> is missing a concept element.</assert>
        <assert test="not(ddi:labl)">Variable <value-of select="@name"/> uses labl — use concept instead. labl is only for catgry elements.</assert>
        <assert test="every $l in distinct-values(ddi:notes[not(@type)]/string(@xml:lang)) satisfies count(ddi:notes[not(@type)][string(@xml:lang) = $l]) &lt;= 1">Variable <value-of select="@name"/> has more than one untyped notes element in one language. Only one untyped note per language is allowed; typed notes (convention:logicMapping, e.g. type="cdl:relevant") are not limited.</assert>
    </rule>

    <!-- Variable group essentials -->
    <rule context="ddi:varGrp">
        <assert test="@name">Variable Group <value-of select="@ID"/> is missing a name attribute.</assert>
        <assert test="@type = 'grid' or @type = 'multipleResp' or @type = 'other' or @type = 'section'">Variable Group <value-of select="@ID"/> has type="<value-of select="@type"/>". Only "grid", "multipleResp", "other", or "section" are supported.</assert>
        <assert test="ddi:concept[normalize-space(.) != '']">Variable Group <value-of select="@ID"/> is missing a concept element.</assert>
        <assert test="not(ddi:labl)">Variable Group <value-of select="@ID"/> uses labl — use concept instead. labl is only for catgry elements.</assert>
    </rule>

    <!-- Category essentials — labl required unless the categorical response is 'multiple' (checkboxes) -->
    <rule context="ddi:catgry">
        <assert test="ddi:catValu">A catgry element is missing catValu.</assert>
        <assert test="ddi:labl or ancestor::ddi:var/ddi:qstn/@responseDomainType = 'multiple'">A catgry element (value: <value-of select="ddi:catValu"/>) is missing a labl (required for responseDomainType="category").</assert>
    </rule>
    <!-- Variable essentials -->
    <rule context="var">
        <assert test="@name">Variable <value-of select="@ID"/> is missing a name attribute.</assert>
        <assert test="@intrvl">Variable <value-of select="@name"/> is missing an intrvl attribute (use "discrete" or "contin").</assert>
        <assert test="qstn/@responseDomainType">Variable <value-of select="@name"/> is missing responseDomainType on qstn.</assert>
        <assert test="qstn/qstnLit">Variable <value-of select="@name"/> is missing a question literal (qstnLit).</assert>
        <assert test="varFormat">Variable <value-of select="@name"/> is missing technical format (varFormat).</assert>
        <assert test="concept[normalize-space(.) != '']">Variable <value-of select="@name"/> is missing a concept element.</assert>
        <assert test="not(labl)">Variable <value-of select="@name"/> uses labl — use concept instead. labl is only for catgry elements.</assert>
        <assert test="every $l in distinct-values(notes[not(@type)]/string(@xml:lang)) satisfies count(notes[not(@type)][string(@xml:lang) = $l]) &lt;= 1">Variable <value-of select="@name"/> has more than one untyped notes element in one language. Only one untyped note per language is allowed; typed notes (convention:logicMapping, e.g. type="cdl:relevant") are not limited.</assert>
    </rule>

    <!-- Variable group essentials -->
    <rule context="varGrp">
        <assert test="@name">Variable Group <value-of select="@ID"/> is missing a name attribute.</assert>
        <assert test="@type = 'grid' or @type = 'multipleResp' or @type = 'other' or @type = 'section'">Variable Group <value-of select="@ID"/> has type="<value-of select="@type"/>". Only "grid", "multipleResp", "other", or "section" are supported.</assert>
        <assert test="concept[normalize-space(.) != '']">Variable Group <value-of select="@ID"/> is missing a concept element.</assert>
        <assert test="not(labl)">Variable Group <value-of select="@ID"/> uses labl — use concept instead. labl is only for catgry elements.</assert>
    </rule>

    <!-- Category essentials — labl required unless the categorical response is 'multiple' (checkboxes) -->
    <rule context="catgry">
        <assert test="catValu">A catgry element is missing catValu.</assert>
        <assert test="labl or ancestor::var/qstn/@responseDomainType = 'multiple'">A catgry element (value: <value-of select="catValu"/>) is missing a labl (required for responseDomainType="category").</assert>
    </rule>
    </pattern>

    <pattern id="logic">
    <!--
        Categorical variables must have catgry elements UNLESS concept/@vocab
        is present, which signals that the categories are defined by an external
        standard code list (e.g. ISO 3166-1 country codes) and need not be
        repeated inline.
    -->
    <rule context="ddi:var">
        <assert test="not(ddi:qstn/@responseDomainType = 'category' or ddi:qstn/@responseDomainType = 'multiple') or ddi:catgry or ddi:concept/@vocab">
            Variable <value-of select="@name"/> (ID: <value-of select="@ID"/>) has a categorical response domain but no catgry elements (add categories or reference an external vocabulary via concept/@vocab).
        </assert>
    </rule>

    <!-- Consistency rules for grid and multiple-response groups -->
    <rule context="ddi:varGrp[@type='grid' or @type='multipleResp']">
        <!-- Per language (#135): each member preQTxt equals the txt with the same xml:lang (none = base). -->
        <assert test="every $id in tokenize(@var, '\s+') satisfies (every $p in //ddi:var[@ID=$id]/ddi:qstn/ddi:preQTxt satisfies normalize-space($p) = normalize-space(string-join(ddi:txt[string(@xml:lang) = string($p/@xml:lang)], ' ')))">
            Consistency Error: Variable Group <value-of select="@ID"/> (<value-of select="@type"/>) text does not match the preQTxt of its member variables.
        </assert>
        <assert test="not(@type='multipleResp') or (every $id in tokenize(@var, '\s+') satisfies (//ddi:var[@ID=$id]/ddi:qstn/@responseDomainType = 'multiple'))">
            Semantic Error: Variables in a multipleResp group (<value-of select="@ID"/>) should have responseDomainType="multiple".
        </assert>
        <assert test="not(@type='grid') or (every $id in tokenize(@var, '\s+') satisfies (//ddi:var[@ID=$id]/ddi:qstn/@responseDomainType = 'category'))">
            Semantic Error: Variables in a grid group (<value-of select="@ID"/>) should have responseDomainType="category".
        </assert>
    </rule>

    <!-- Parent "other" varGrp rules (semi-open question hierarchy) -->
    <rule context="ddi:varGrp[@type='other']">
        <assert test="@var or @varGrp">
            Parent varGrp <value-of select="@ID"/> (type="other") must reference variables (@var) or child groups (@varGrp).
        </assert>
        <assert test="not(@varGrp) or (every $id in tokenize(@varGrp, '\s+') satisfies //ddi:varGrp[@ID=$id])">
            Parent varGrp <value-of select="@ID"/> references a child varGrp that does not exist.
        </assert>
        <assert test="not(@var) or (every $id in tokenize(@var, '\s+') satisfies //ddi:var[@ID=$id])">
            Parent varGrp <value-of select="@ID"/> references a variable that does not exist.
        </assert>
    </rule>
    <!--
        Categorical variables must have catgry elements UNLESS concept/@vocab
        is present, which signals that the categories are defined by an external
        standard code list (e.g. ISO 3166-1 country codes) and need not be
        repeated inline.
    -->
    <rule context="var">
        <assert test="not(qstn/@responseDomainType = 'category' or qstn/@responseDomainType = 'multiple') or catgry or concept/@vocab">
            Variable <value-of select="@name"/> (ID: <value-of select="@ID"/>) has a categorical response domain but no catgry elements (add categories or reference an external vocabulary via concept/@vocab).
        </assert>
    </rule>

    <!-- Consistency rules for grid and multiple-response groups -->
    <rule context="varGrp[@type='grid' or @type='multipleResp']">
        <!-- Per language (#135): each member preQTxt equals the txt with the same xml:lang (none = base). -->
        <assert test="every $id in tokenize(@var, '\s+') satisfies (every $p in //var[@ID=$id]/qstn/preQTxt satisfies normalize-space($p) = normalize-space(string-join(txt[string(@xml:lang) = string($p/@xml:lang)], ' ')))">
            Consistency Error: Variable Group <value-of select="@ID"/> (<value-of select="@type"/>) text does not match the preQTxt of its member variables.
        </assert>
        <assert test="not(@type='multipleResp') or (every $id in tokenize(@var, '\s+') satisfies (//var[@ID=$id]/qstn/@responseDomainType = 'multiple'))">
            Semantic Error: Variables in a multipleResp group (<value-of select="@ID"/>) should have responseDomainType="multiple".
        </assert>
        <assert test="not(@type='grid') or (every $id in tokenize(@var, '\s+') satisfies (//var[@ID=$id]/qstn/@responseDomainType = 'category'))">
            Semantic Error: Variables in a grid group (<value-of select="@ID"/>) should have responseDomainType="category".
        </assert>
    </rule>

    <!-- Parent "other" varGrp rules (semi-open question hierarchy) -->
    <rule context="varGrp[@type='other']">
        <assert test="@var or @varGrp">
            Parent varGrp <value-of select="@ID"/> (type="other") must reference variables (@var) or child groups (@varGrp).
        </assert>
        <assert test="not(@varGrp) or (every $id in tokenize(@varGrp, '\s+') satisfies //varGrp[@ID=$id])">
            Parent varGrp <value-of select="@ID"/> references a child varGrp that does not exist.
        </assert>
        <assert test="not(@var) or (every $id in tokenize(@var, '\s+') satisfies //var[@ID=$id])">
            Parent varGrp <value-of select="@ID"/> references a variable that does not exist.
        </assert>
    </rule>
    </pattern>

    <pattern id="other_variables">
    <!--
        Rules for "_other" (semi-open / halb-offen) variables.
        Convention: a var whose @name ends in "_other" is a free-text
        specification field linked to a base variable or group by naming
        convention (e.g. geschlecht_other → geschlecht). Companion facts
        (type/intrvl/format) come from type:text in the registry.
    -->
    <rule context="ddi:var[ends-with(@name, '_other')]">
        <assert test="ddi:qstn/@responseDomainType = 'text'">
            Variable <value-of select="@name"/> ends in "_other" but has responseDomainType="<value-of select="ddi:qstn/@responseDomainType"/>". Expected "text".
        </assert>
        <assert test="@intrvl = 'discrete'">
            Variable <value-of select="@name"/> ends in "_other" but has intrvl="<value-of select="@intrvl"/>". Expected "discrete".
        </assert>
        <assert test="ddi:varFormat/@type = 'character'">
            Variable <value-of select="@name"/> ends in "_other" but has varFormat type="<value-of select="ddi:varFormat/@type"/>". Expected "character".
        </assert>
        <assert test="//ddi:var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))] or //ddi:varGrp[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]">
            Variable <value-of select="@name"/> ends in "_other" but no matching base variable or group named "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" was found.
        </assert>
        <assert test="not(//ddi:var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]) or //ddi:var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]/ddi:catgry[ddi:catValu = 'other'] or //ddi:varGrp[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other')) and @type != 'other']">
            Variable <value-of select="@name"/>: the base variable "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" must have a catgry with catValu="other" (convention for round-trip conversion).
        </assert>
        <assert test="not(//ddi:varGrp[@type='multipleResp' and contains(concat(' ', @var, ' '), concat(' ', current()/@ID, ' '))])">
            Variable <value-of select="@name"/> (text _other) must not be a member of a multipleResp group. It should be a standalone variable outside the group.
        </assert>
        <assert test="not(//ddi:var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]/ddi:concept/@vocab)">
            Variable <value-of select="@name"/>: the base variable "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" uses concept/@vocab (long list). Long list and _other cannot be combined.
        </assert>
    </rule>
    <!--
        Rules for "_other" (semi-open / halb-offen) variables.
        Convention: a var whose @name ends in "_other" is a free-text
        specification field linked to a base variable or group by naming
        convention (e.g. geschlecht_other → geschlecht). Companion facts
        (type/intrvl/format) come from type:text in the registry.
    -->
    <rule context="var[ends-with(@name, '_other')]">
        <assert test="qstn/@responseDomainType = 'text'">
            Variable <value-of select="@name"/> ends in "_other" but has responseDomainType="<value-of select="qstn/@responseDomainType"/>". Expected "text".
        </assert>
        <assert test="@intrvl = 'discrete'">
            Variable <value-of select="@name"/> ends in "_other" but has intrvl="<value-of select="@intrvl"/>". Expected "discrete".
        </assert>
        <assert test="varFormat/@type = 'character'">
            Variable <value-of select="@name"/> ends in "_other" but has varFormat type="<value-of select="varFormat/@type"/>". Expected "character".
        </assert>
        <assert test="//var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))] or //varGrp[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]">
            Variable <value-of select="@name"/> ends in "_other" but no matching base variable or group named "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" was found.
        </assert>
        <assert test="not(//var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]) or //var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]/catgry[catValu = 'other'] or //varGrp[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other')) and @type != 'other']">
            Variable <value-of select="@name"/>: the base variable "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" must have a catgry with catValu="other" (convention for round-trip conversion).
        </assert>
        <assert test="not(//varGrp[@type='multipleResp' and contains(concat(' ', @var, ' '), concat(' ', current()/@ID, ' '))])">
            Variable <value-of select="@name"/> (text _other) must not be a member of a multipleResp group. It should be a standalone variable outside the group.
        </assert>
        <assert test="not(//var[@name = substring(current()/@name, 1, string-length(current()/@name) - string-length('_other'))]/concept/@vocab)">
            Variable <value-of select="@name"/>: the base variable "<value-of select="substring(@name, 1, string-length(@name) - string-length('_other'))"/>" uses concept/@vocab (long list). Long list and _other cannot be combined.
        </assert>
    </rule>
    </pattern>

    <pattern id="cdl_notes">
    <rule context="ddi:notes[starts-with(@type, 'cdl:')]">
        <assert test="@type = 'cdl:appearance' or @type = 'cdl:constraint' or @type = 'cdl:constraint_message' or @type = 'cdl:default' or @type = 'cdl:exclusive' or @type = 'cdl:hint' or @type = 'cdl:language' or @type = 'cdl:list' or @type = 'cdl:note_names' or @type = 'cdl:or_other' or @type = 'cdl:other_label' or @type = 'cdl:parameters' or @type = 'cdl:position' or @type = 'cdl:relevant' or @type = 'cdl:required' or @type = 'cdl:row' or @type = 'cdl:row_appearance' or @type = 'cdl:row_hint' or @type = 'cdl:row_label' or @type = 'cdl:row_relevant' or @type = 'cdl:setting'">Note type "<value-of select="@type"/>" is not in the CDL vocabulary (cdl:appearance, cdl:constraint, cdl:constraint_message, cdl:default, cdl:exclusive, cdl:hint, cdl:language, cdl:list, cdl:note_names, cdl:or_other, cdl:other_label, cdl:parameters, cdl:position, cdl:relevant, cdl:required, cdl:row, cdl:row_appearance, cdl:row_hint, cdl:row_label, cdl:row_relevant, cdl:setting).</assert>
        <assert test="not(@type = 'cdl:constraint') or @subject = 'xlsform-xpath'">A cdl:constraint note needs subject="xlsform-xpath": its text is an expression in that syntax.</assert>
        <assert test="not(@type = 'cdl:language') or normalize-space(@subject) != ''">A cdl:language note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:position') or normalize-space(@subject) != ''">A cdl:position note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:relevant') or @subject = 'xlsform-xpath'">A cdl:relevant note needs subject="xlsform-xpath": its text is an expression in that syntax.</assert>
        <assert test="not(@type = 'cdl:row') or normalize-space(@subject) != ''">A cdl:row note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_appearance') or normalize-space(@subject) != ''">A cdl:row_appearance note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_hint') or normalize-space(@subject) != ''">A cdl:row_hint note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_label') or normalize-space(@subject) != ''">A cdl:row_label note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_relevant') or normalize-space(@subject) != ''">A cdl:row_relevant note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:setting') or normalize-space(@subject) != ''">A cdl:setting note needs a subject: the name of what it holds.</assert>
    </rule>
    <rule context="notes[starts-with(@type, 'cdl:')]">
        <assert test="@type = 'cdl:appearance' or @type = 'cdl:constraint' or @type = 'cdl:constraint_message' or @type = 'cdl:default' or @type = 'cdl:exclusive' or @type = 'cdl:hint' or @type = 'cdl:language' or @type = 'cdl:list' or @type = 'cdl:note_names' or @type = 'cdl:or_other' or @type = 'cdl:other_label' or @type = 'cdl:parameters' or @type = 'cdl:position' or @type = 'cdl:relevant' or @type = 'cdl:required' or @type = 'cdl:row' or @type = 'cdl:row_appearance' or @type = 'cdl:row_hint' or @type = 'cdl:row_label' or @type = 'cdl:row_relevant' or @type = 'cdl:setting'">Note type "<value-of select="@type"/>" is not in the CDL vocabulary (cdl:appearance, cdl:constraint, cdl:constraint_message, cdl:default, cdl:exclusive, cdl:hint, cdl:language, cdl:list, cdl:note_names, cdl:or_other, cdl:other_label, cdl:parameters, cdl:position, cdl:relevant, cdl:required, cdl:row, cdl:row_appearance, cdl:row_hint, cdl:row_label, cdl:row_relevant, cdl:setting).</assert>
        <assert test="not(@type = 'cdl:constraint') or @subject = 'xlsform-xpath'">A cdl:constraint note needs subject="xlsform-xpath": its text is an expression in that syntax.</assert>
        <assert test="not(@type = 'cdl:language') or normalize-space(@subject) != ''">A cdl:language note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:position') or normalize-space(@subject) != ''">A cdl:position note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:relevant') or @subject = 'xlsform-xpath'">A cdl:relevant note needs subject="xlsform-xpath": its text is an expression in that syntax.</assert>
        <assert test="not(@type = 'cdl:row') or normalize-space(@subject) != ''">A cdl:row note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_appearance') or normalize-space(@subject) != ''">A cdl:row_appearance note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_hint') or normalize-space(@subject) != ''">A cdl:row_hint note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_label') or normalize-space(@subject) != ''">A cdl:row_label note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:row_relevant') or normalize-space(@subject) != ''">A cdl:row_relevant note needs a subject: the name of what it holds.</assert>
        <assert test="not(@type = 'cdl:setting') or normalize-space(@subject) != ''">A cdl:setting note needs a subject: the name of what it holds.</assert>
    </rule>
    </pattern>

    <pattern id="cdl_note_uniqueness">
    <rule context="ddi:var | ddi:varGrp">
        <assert test="every $t in distinct-values(ddi:notes[starts-with(@type, 'cdl:')]/@type) satisfies every $l in distinct-values(ddi:notes[@type = $t]/string(@xml:lang)) satisfies count(ddi:notes[@type = $t][string(@xml:lang) = $l]) &lt;= 1"><value-of select="@name"/> has more than one note of one cdl: type in one language.</assert>
    </rule>
    <rule context="ddi:stdyDscr">
        <assert test="every $t in distinct-values(ddi:notes[starts-with(@type, 'cdl:')]/@type) satisfies every $s in distinct-values(ddi:notes[@type = $t]/string(@subject)) satisfies every $l in distinct-values(ddi:notes[@type = $t][string(@subject) = $s]/string(@xml:lang)) satisfies count(ddi:notes[@type = $t][string(@subject) = $s][string(@xml:lang) = $l]) &lt;= 1">The study has more than one note of one cdl: type about one subject in one language.</assert>
    </rule>
    <rule context="var | varGrp">
        <assert test="every $t in distinct-values(notes[starts-with(@type, 'cdl:')]/@type) satisfies every $l in distinct-values(notes[@type = $t]/string(@xml:lang)) satisfies count(notes[@type = $t][string(@xml:lang) = $l]) &lt;= 1"><value-of select="@name"/> has more than one note of one cdl: type in one language.</assert>
    </rule>
    <rule context="stdyDscr">
        <assert test="every $t in distinct-values(notes[starts-with(@type, 'cdl:')]/@type) satisfies every $s in distinct-values(notes[@type = $t]/string(@subject)) satisfies every $l in distinct-values(notes[@type = $t][string(@subject) = $s]/string(@xml:lang)) satisfies count(notes[@type = $t][string(@subject) = $s][string(@xml:lang) = $l]) &lt;= 1">The study has more than one note of one cdl: type about one subject in one language.</assert>
    </rule>
    </pattern>

</schema>
